
DEFINE_ACTION_FUNCTION import_iwd_items BEGIN

//
// add .bam resources and similar stuff
//

COPY ~%MOD_FOLDER%/data/iwd_items/shared~ ~override~

//
// add the items
//

ACTION_IF (FILE_EXISTS_IN_GAME ~boot11.itm~) BEGIN
  COPY_EXISTING ~boot11.itm~ ~override~
    WRITE_LONG 0x34 3000
END

ACTION_IF (FILE_EXISTS_IN_GAME ~belt10.itm~) BEGIN
  COPY_EXISTING ~belt10.itm~ ~override~
    WRITE_LONG 0x34 8000
END

COPY ~%MOD_FOLDER%/data/iwd_items/amulbar.itm~ ~override/d5ambar.itm~
  SAY NAME2 @1011
  SAY DESC @1012

OUTER_SET spell_ids = IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_COURAGE~)
ACTION_IF !(spell_ids = 0 - 1) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_EMOTION_COURAGE~ RET spell_res END
  COPY ~%MOD_FOLDER%/data/iwd_items/amulbra.itm~ ~override/d5ambar.itm~
   SAY NAME2 @1021
   SAY DESC @1022
   LPF ALTER_EFFECT INT_VAR match_opcode = 148 STR_VAR resource = EVAL ~%spell_res%~ END
END

COPY ~%MOD_FOLDER%/data/iwd_items/beetshld.itm~ ~override/d5btshld~
  SAY NAME2 @1041
  SAY DESC @1042

OUTER_SET spell_ids = IDS_OF_SYMBOL (~spell~ ~CLERIC_CIRCLE_OF_BONES~)
ACTION_IF !(spell_ids = 0 - 1) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_CIRCLE_OF_BONES~ RET spell_res END
  COPY ~%MOD_FOLDER%/data/iwd_items/beltbon.itm~ ~override/d5bltbon.itm~
   SAY NAME2 @1051
   SAY DESC @1052
   LPF ALTER_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~sppr323~ resource = EVAL ~%spell_res%~ END
END

COPY ~%MOD_FOLDER%/data/iwd_items/bess.itm~ ~override/d5bess.itm~
  SAY NAME2 @1641
  SAY DESC @1642

COPY ~%MOD_FOLDER%/data/iwd_items/biteme.itm~ ~override/d5biteme.itm~
  SAY NAME2 @1061
  SAY DESC @1062

COPY ~%MOD_FOLDER%/data/iwd_items/boneam.itm~ ~override/d5boneam.itm~
  SAY NAME2 @1071
  SAY DESC @1072

COPY ~%MOD_FOLDER%/data/iwd_items/bootman.itm~ ~override/d5bootma.itm~
  SAY NAME2 @1081
  SAY DESC @1082

COPY ~%MOD_FOLDER%/data/iwd_items/bootmoa.itm~ ~override/d5bootmo.itm~
  SAY NAME2 @1091
  SAY DESC @1092

COPY ~%MOD_FOLDER%/data/iwd_items/bwtalis.itm~ ~override/d5talis.itm~
  SAY NAME2 @1101
  SAY DESC @1102

COPY ~%MOD_FOLDER%/data/iwd_items/cdrelm.itm~ ~override/d5cdrelm.itm~
  SAY NAME2 @1111
  SAY DESC @1112

OUTER_SET spell_ids = IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_COURAGE~)
ACTION_IF !(spell_ids = 0 - 1) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_EMOTION_COURAGE~ RET spell_res END
  COPY ~%MOD_FOLDER%/data/iwd_items/cittern.itm~ ~override/d5cittrn.itm~
   SAY NAME2 @1121
   SAY DESC @1122
   LPF ALTER_EFFECT INT_VAR match_opcode = 148 STR_VAR resource = EVAL ~%spell_res%~ END
END

COPY ~%MOD_FOLDER%/data/iwd_items/clckbs.itm~ ~override/d5clckbs.itm~
  SAY NAME2 @1131
  SAY DESC @1132

OUTER_SET spell_ids = IDS_OF_SYMBOL (~spell~ ~CLERIC_WHIRLWIND~)
ACTION_IF !(spell_ids = 0 - 1) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_WHIRLWIND~ RET spell_res END
  COPY ~%MOD_FOLDER%/data/iwd_items/cone.itm~ ~override/d5cone.itm~
   SAY NAME2 @1141
   SAY DESC @1142
   LPF ALTER_EFFECT INT_VAR match_opcode = 148 STR_VAR match_resource = ~sppr617~ resource = EVAL ~%spell_res%~ END
END

COPY ~%MOD_FOLDER%/data/iwd_items/corello.itm~ ~override/d5corel.itm~
  SAY NAME2 @1151
  SAY DESC @1152
  WRITE_LONG 0x34 1500

COPY ~%MOD_FOLDER%/data/iwd_items/dazer.itm~ ~override/d5dazer.itm~
  SAY NAME2 @1161
  SAY DESC @1162
  WRITE_LONG 0x34 3000

COPY ~%MOD_FOLDER%/data/iwd_items/diver.itm~ ~override/d5diver.itm~
  SAY NAME2 @1171
  SAY DESC @1172

COPY ~%MOD_FOLDER%/data/iwd_items/erevain.itm~ ~override/d5erevan.itm~
  SAY NAME2 @1181
  SAY DESC @1182

COPY ~%MOD_FOLDER%/data/iwd_items/fkiller.itm~ ~override/d5fkillr.itm~
  SAY NAME2 @1191
  SAY DESC @1192

COPY ~%MOD_FOLDER%/data/iwd_items/force.itm~ ~override/d5force.itm~
  SAY NAME2 @1201
  SAY DESC @1202
  WRITE_LONG 0x34 15

COPY ~%MOD_FOLDER%/data/iwd_items/helmpat.itm~ ~override/d5hlmpat.itm~
  SAY NAME1 @1631
  SAY NAME2 @1631
  SAY DESC @1632
  WRITE_LONG 0x34 2500

COPY ~%MOD_FOLDER%/data/iwd_items/holdfst.itm~ ~override/d5hldfst.itm~
  SAY NAME2 @1211
  SAY DESC @1212

COPY ~%MOD_FOLDER%/data/iwd_items/intrces.itm~ ~override/d5intrcs.itm~
  SAY NAME2 @1221
  SAY DESC @1222

COPY ~%MOD_FOLDER%/data/iwd_items/kreswrd.itm~ ~override/d5krswrd.itm~
  SAY NAME2 @1231
  SAY DESC @1232
  WRITE_LONG 0x34 2500

COPY ~%MOD_FOLDER%/data/iwd_items/lucky.itm~ ~override/d5lucky.itm~
  SAY NAME2 @1241
  SAY DESC @1242

COPY ~%MOD_FOLDER%/data/iwd_items/lyre.itm~ ~override/d5lyre.itm~
  SAY NAME2 @1251
  SAY DESC @1252
  WRITE_LONG 0x34 4000

COPY ~%MOD_FOLDER%/data/iwd_items/mhorn.itm~ ~override/d5mhorn.itm~
  SAY NAME2 @1261
  SAY DESC @1262

COPY ~%MOD_FOLDER%/data/iwd_items/nature.itm~ ~override/d5nature.itm~
  SAY NAME2 @1271
  SAY DESC @1272

COPY ~%MOD_FOLDER%/data/iwd_items/ohbrac01.itm~ ~override/d5ohbrc1.itm~
  SAY NAME2 @1281
  SAY DESC @1282

COPY ~%MOD_FOLDER%/data/iwd_items/ohioun02.itm~ ~override/d5ohiun2.itm~
  SAY NAME2 @1291
  SAY DESC @1292

COPY ~%MOD_FOLDER%/data/iwd_items/peaceke.itm~ ~override/d5peacek.itm~
  SAY NAME2 @1301
  SAY DESC @1302
  WRITE_LONG 0x34 8000

COPY ~%MOD_FOLDER%/data/iwd_items/poker.itm~ ~override/d5poker.itm~
  SAY NAME2 @1311
  SAY DESC @1312

// ***** too good?
COPY ~%MOD_FOLDER%/data/iwd_items/shboots.itm~ ~override/d5shboot.itm~
  SAY NAME2 @1321
  SAY DESC @1322

// ***** too good?
COPY ~%MOD_FOLDER%/data/iwd_items/shstaff.itm~ ~override/d5shstaf.itm~
  SAY NAME2 @1331
  SAY DESC @1332

COPY ~%MOD_FOLDER%/data/iwd_items/slinged.itm~ ~override/d5slnged.itm~
  SAY NAME2 @1341
  SAY DESC @1342

COPY ~%MOD_FOLDER%/data/iwd_items/solonor.itm~ ~override/d5solon.itm~
  SAY NAME2 @1351
  SAY DESC @1352
  WRITE_LONG 0x34 750

COPY ~%MOD_FOLDER%/data/iwd_items/spine.itm~ ~override/d5spine.itm~
  SAY NAME2 @1361
  SAY DESC @1362

COPY ~%MOD_FOLDER%/data/iwd_items/stafhmg.itm~ ~override/d5stfhmg.itm~
  SAY NAME2 @1371
  SAY DESC @1372

COPY ~%MOD_FOLDER%/data/iwd_items/stout.itm~ ~override/d5stout.itm~
  SAY NAME2 @1381
  SAY DESC @1382

COPY ~%MOD_FOLDER%/data/iwd_items/trnbolt.itm~ ~override/d5trbolt.itm~
  SAY NAME2 @1391
  SAY DESC @1392
  WRITE_LONG 0x34 30

COPY ~%MOD_FOLDER%/data/iwd_items/turodah.itm~ ~override/d5turod.itm~
  SAY NAME2 @1401
  SAY DESC @1402

COPY ~%MOD_FOLDER%/data/iwd_items/u1ham2a.itm~ ~override/d51ham2a.itm~
  SAY NAME2 @1411
  SAY DESC @1412
  WRITE_LONG 0x34 2000

COPY ~%MOD_FOLDER%/data/iwd_items/u1hax4B.itm~ ~override/d51hax4b.itm~
  SAY NAME2 @1621
  SAY DESC @1622
  WRITE_ASCII 0x3a ~D51HAX4B~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/uarow2a.itm~ ~override/d5arow2a.itm~
  SAY NAME2 @1421
  SAY DESC @1422

COPY ~%MOD_FOLDER%/data/iwd_items/udagg2a.itm~ ~override/d5dagg2a.itm~
  SAY NAME2 @1431
  SAY DESC @1432
  WRITE_ASCII 0x3a ~D5DAGG2A~ #8
  WRITE_LONG 0x34 2000

COPY ~%MOD_FOLDER%/data/iwd_items/udart3b.itm~ ~override/d5dart3b.itm~
  SAY NAME2 @1441
  SAY DESC @1442

COPY ~%MOD_FOLDER%/data/iwd_items/uflal2a.itm~ ~override/d5flal2a.itm~
  SAY NAME2 @1451
  SAY DESC @1452
//  WRITE_ASCII 0x3a ~D5FLAL2A~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/uhalb3a.itm~ ~override/d5halb3a.itm~
  SAY NAME2 @1461
  SAY DESC @1462
  WRITE_ASCII 0x3a ~D5HALB3A~ #8
  WRITE_LONG 0x34 2000

COPY ~%MOD_FOLDER%/data/iwd_items/uhxbw3a.itm~ ~override/d5hxbw3a.itm~
  SAY NAME2 @1471
  SAY DESC @1472
  WRITE_ASCII 0x3a ~D5HXBW3A~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/ulbow3c.itm~ ~override/d5lbow3c.itm~
  SAY NAME2 @1481
  SAY DESC @1482
  WRITE_ASCII 0x3a ~D5LBOW3C~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/ulxbw3a.itm~ ~override/d5lxbw3a.itm~
  SAY NAME2 @1491
  SAY DESC @1492
  WRITE_ASCII 0x3a ~D5LXBW3A~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/umhulk.itm~ ~override/d5umhulk.itm~
  SAY NAME1 @1501
  SAY NAME2 @1501
  SAY DESC @1502
  WRITE_LONG 0x34 5000

COPY ~%MOD_FOLDER%/data/iwd_items/umstr2b.itm~ ~override/d5mstr2b.itm~
  SAY NAME2 @1511
  SAY DESC @1512
  WRITE_ASCII 0x3a ~D5MSTR2B~ #8
  WRITE_LONG 0x34 3600

COPY ~%MOD_FOLDER%/data/iwd_items/uring3b.itm~ ~override/d5ring3b.itm~
  SAY NAME2 @1521
  SAY DESC @1522
  WRITE_ASCII 0x3a ~D5RING3B~ #8

 COPY ~%MOD_FOLDER%/data/iwd_items/urobe1a.itm~ ~override/d5robe1a.itm~
  SAY NAME2 @1531
  SAY DESC @1532
  WRITE_ASCII 0x3a ~D5ROBE1A~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/usltr2a.itm~ ~override/d5sltr2a.itm~
  SAY NAME2 @1541
  SAY DESC @1542
  WRITE_ASCII 0x3a ~D5SLTR2A~ #8

COPY ~%MOD_FOLDER%/data/iwd_items/uspot1a.itm~ ~override/d5spot1a.itm~
  SAY NAME2 @1551
  SAY DESC @1552

COPY ~%MOD_FOLDER%/data/iwd_items/uspot3c.itm~ ~override/d5spot3c.itm~
  SAY NAME2 @1561
  SAY DESC @1562

COPY ~%MOD_FOLDER%/data/iwd_items/uspot4b.itm~ ~override/d5spot4b.itm~
  SAY NAME2 @1571
  SAY DESC @1572

COPY ~%MOD_FOLDER%/data/iwd_items/wandmis.itm~ ~override/d5wndmis.itm~
  SAY NAME2 @1581
  SAY DESC @1582

COPY ~%MOD_FOLDER%/data/iwd_items/zze6pe.itm~ ~override/d5zze6pe.itm~
  SAY NAME2 @1591
  SAY DESC @1592

COPY ~%MOD_FOLDER%/data/iwd_items/zzm5mh.itm~ ~override/d5zzm5mh.itm~
  SAY NAME2 @1601
  SAY DESC @1602

COPY ~%MOD_FOLDER%/data/iwd_items/zzs6sc.itm~ ~override/d5zzs6sc.itm~
  SAY NAME2 @1611
  SAY DESC @1612

END	//	end define function
